baseURL = 'https://dawidg.com/'
languageCode = 'en-us'
title = "Dawid's Wiki"
theme = 'hugo-book'

enableGitInfo = true

[params]
  BookTheme = 'auto'
  BookToC = true
  BookSection = 'docs'
  BookSearch = true
  BookComments = false
  BookEditLink = 'https://github.com/dawid-gierlachowski/dawidg-wiki/edit/main/{{ .Path }}'

[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 2
  endLevel = 4
